apiVersion: v1
kind: Service
metadata:
  name: school-middleware
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: school-middleware
  type: NodePort