apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: school-middleware
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: 'kustomize/apps/school-middleware/overlays/'
    repoURL: 'https://github.com/pio-ste/school-gitops-kubernetes.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
