apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: school-middleware
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: school-middleware
    server: 'https://kubernetes.default.svc'
  source:
    path: 'kustomize/apps/school-middleware/base'
    repoURL: 'https://github.com/pio-ste/school-gitops-kubernetes.git'
    targetRevision: HEAD
  project: school-middleware
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
